# Generated by Django 3.2.4 on 2021-06-13 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_tester'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tester',
        ),
    ]
