# Generated by Django 3.2.4 on 2021-06-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='testing',
            field=models.CharField(default='default name', max_length=100),
        ),
    ]
