# Generated by Django 2.2.20 on 2021-05-05 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='api',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(default='default name', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='name_id',
            field=models.CharField(default='default name_id', max_length=100),
        ),
    ]
