# Generated by Django 3.2.4 on 2021-06-19 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_post_testing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='testing',
        ),
    ]
