# Generated by Django 2.2.20 on 2021-05-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210505_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='first_message',
            field=models.CharField(default='hello my friend', max_length=100),
        ),
    ]
