# Generated by Django 2.2.20 on 2021-05-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_post_running'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='running',
            field=models.BooleanField(),
        ),
    ]
