# Generated by Django 2.2.20 on 2021-05-22 13:50

from django.db import migrations
import tablefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210522_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='testa_table',
            field=tablefield.fields.TableField(blank=True, default=dict, verbose_name='TestTable'),
        ),
    ]
