# Generated by Django 2.2.20 on 2021-05-22 13:54

from django.db import migrations
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_post_testa_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='testa_table',
            field=hashid_field.field.HashidField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, prefix=''),
        ),
    ]
