# Generated by Django 2.2.20 on 2021-05-22 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210522_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='testa_table',
            new_name='test_set',
        ),
    ]
