# Generated by Django 2.2.20 on 2021-05-22 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210522_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='test_set',
        ),
    ]
