# Generated by Django 2.2.20 on 2021-05-22 14:23

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_post_test_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='message_pairs',
            field=jsonfield.fields.JSONField(default=list),
        ),
    ]
