# Generated by Django 2.2.20 on 2021-05-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_post_message_pairs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='running',
            field=models.BooleanField(default=False),
        ),
    ]
